apiVersion: v1
entries:
  cpi-auth:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-03-30T00:21:32.169900729Z"
    description: CPI Auth - Identity and Access Management platform
    digest: 4bd7d21c81f9d239b0a6d58c3b21d3040d5298fd6de165b537c449839798244a
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-30T00:21:32.168909105Z"
