apiVersion: v1
entries:
  cpi-auth:
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2026-03-30T20:56:44.284576927Z"
    description: CPI Auth - Identity and Access Management platform
    digest: 20532867a76567b8fb60bd03c45c158cc2984620da51cdaf963aa2f903792f8e
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2026-03-30T20:56:44.283794996Z"
    description: CPI Auth - Identity and Access Management platform
    digest: 26482a7bf44c97cb6961c23c431fde244d8d14a9e73ca1a366b96e156d3ccd78
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2026-03-30T20:56:44.282967168Z"
    description: CPI Auth - Identity and Access Management platform
    digest: 74eb46c53db682beae810fd78c209173d3ca93f340584fdfb5f8b285483554e1
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-03-30T20:56:44.282121924Z"
    description: CPI Auth - Identity and Access Management platform
    digest: ecd32d19b2aad771392951890e5475f8619f681c91eda4cc0ed96d81189ba2d2
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-30T20:56:44.280903958Z"
