apiVersion: v1
entries:
  cpi-auth:
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2026-03-30T20:28:21.771662763Z"
    description: CPI Auth - Identity and Access Management platform
    digest: b8a33aac561531b8293f00d21dfc789df913363ae31517f32378e1d8ad0b3a12
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2026-03-30T20:28:21.769553114Z"
    description: CPI Auth - Identity and Access Management platform
    digest: 74eb46c53db682beae810fd78c209173d3ca93f340584fdfb5f8b285483554e1
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-03-30T20:28:21.768642169Z"
    description: CPI Auth - Identity and Access Management platform
    digest: ecd32d19b2aad771392951890e5475f8619f681c91eda4cc0ed96d81189ba2d2
    home: https://github.com/cpi-technologies-gmbh/cpi-auth
    keywords:
    - iam
    - authentication
    - authorization
    - identity
    maintainers:
    - name: CPI Technologies GmbH
      url: https://github.com/cpi-technologies-gmbh
    name: cpi-auth
    sources:
    - https://github.com/cpi-technologies-gmbh/cpi-auth
    type: application
    urls:
    - https://cpi-technologies-gmbh.github.io/CPI-Auth/charts/cpi-auth-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-30T20:28:21.767643822Z"
