apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpi-auth.fullname" . }}-core
  labels:
    {{- include "cpi-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
type: Opaque
data:
  database-password: {{ include "cpi-auth.databasePassword" . | b64enc | quote }}
  encryption-key: {{ default (randAlphaNum 32) .Values.core.config.security.encryptionKey | b64enc | quote }}
  jwt-private-key: {{ default "replace-me-with-real-key" .Values.core.config.security.jwtPrivateKey | b64enc | quote }}
  {{- if .Values.core.config.smtp.password }}
  smtp-password: {{ .Values.core.config.smtp.password | b64enc | quote }}
  {{- end }}
