apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpi-auth.fullname" . }}-core
  labels:
    {{- include "cpi-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cpi-auth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
