<script lang="ts">
	import { page } from '$app/stores';
	import { env } from '$env/dynamic/public';
	import { branding } from '$lib/stores';
	import AuthLayout from '$lib/components/AuthLayout.svelte';
	import Alert from '$lib/components/Alert.svelte';

	let code = $state($page.url.searchParams.get('code') || '');
	let loading = $state(false);
	let error = $state('');
	let success = $state(false);

	// Format input as XXXX-XXXX
	function formatCode(value: string): string {
		const clean = value.replace(/[^A-Za-z0-9]/g, '').toUpperCase().slice(0, 8);
		if (clean.length > 4) {
			return clean.slice(0, 4) + '-' + clean.slice(4);
		}
		return clean;
	}

	function handleInput(e: Event) {
		const input = e.target as HTMLInputElement;
		code = formatCode(input.value);
		input.value = code;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		error = '';

		const cleanCode = code.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
		if (cleanCode.length !== 8) {
			error = 'Please enter the complete 8-character code.';
			return;
		}

		loading = true;

		try {
			// Authorize directly. The endpoint accepts either a Bearer token
			// (admin UI) or the session cookie set by the browser login flow.
			const apiUrl = env.PUBLIC_API_URL || '';
			const headers: Record<string, string> = { 'Content-Type': 'application/json' };

			// Forward an admin-UI Bearer token from localStorage if available.
			try {
				const bearer = localStorage.getItem('access_token');
				if (bearer) headers['Authorization'] = `Bearer ${bearer}`;
			} catch {}

			const res = await fetch(`${apiUrl}/oauth/device/authorize`, {
				method: 'POST',
				credentials: 'include',
				headers,
				body: JSON.stringify({ user_code: code }),
			});

			if (res.status === 401) {
				// Not logged in — bounce through the login UI and come back here.
				const returnUrl = `/device?code=${code}`;
				window.location.href = `/login?return_to=${encodeURIComponent(returnUrl)}`;
				return;
			}

			if (!res.ok) {
				const data = await res.json().catch(() => ({}));
				error = data.error_description || data.error || 'Failed to authorize device.';
				return;
			}

			success = true;
		} catch (err) {
			error = 'Network error. Please try again.';
		} finally {
			loading = false;
		}
	}
</script>

<AuthLayout maxWidth="sm">
	<div class="space-y-6">
		<div class="text-center">
			<h1 class="text-2xl font-bold" style="color: var(--af-color-text)">
				Authorize Device
			</h1>
			<p class="mt-2 text-sm" style="color: var(--af-color-text-muted)">
				Enter the code shown in your terminal to authorize CPI Auth CLI.
			</p>
		</div>

		{#if success}
			<div class="rounded-lg border border-green-500/30 bg-green-500/10 p-6 text-center">
				<svg class="mx-auto h-12 w-12 text-green-400 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
				</svg>
				<h2 class="text-lg font-semibold text-green-400 mb-1">Device Authorized</h2>
				<p class="text-sm" style="color: var(--af-color-text-muted)">
					You can close this window and return to your terminal.
				</p>
			</div>
		{:else}
			{#if error}
				<Alert type="error" message={error} dismissible />
			{/if}

			<form onsubmit={handleSubmit} class="space-y-4">
				<div>
					<label for="code" class="af-label">Device Code</label>
					<input
						id="code"
						type="text"
						value={code}
						oninput={handleInput}
						placeholder="XXXX-XXXX"
						class="af-input text-center text-2xl font-mono tracking-[0.3em] uppercase"
						maxlength="9"
						autocomplete="off"
					/>
				</div>

				<button
					type="submit"
					class="af-btn af-btn-primary w-full"
					disabled={loading || code.replace(/[^A-Za-z0-9]/g, '').length !== 8}
				>
					{#if loading}
						Authorizing...
					{:else}
						Authorize
					{/if}
				</button>
			</form>

			<p class="text-center text-xs" style="color: var(--af-color-text-muted)">
				This code was generated by CPI Auth CLI.<br/>
				Only authorize if you initiated this request.
			</p>
		{/if}
	</div>
</AuthLayout>
